#!/bin/sh -e

NAME=unifi
BASEDIR=/usr/lib/${NAME}

[ -f /etc/default/${NAME} ] && . /etc/default/${NAME}

DATADIR=${UNIFI_DATA_DIR:-/var/lib/$NAME}
LOGDIR=${UNIFI_LOG_DIR:-/var/log/$NAME}
RUNDIR=${UNIFI_RUN_DIR:-/var/run/$NAME}

[ -z "${UNIFI_DATA_DIR}" ] || DATADIR=${UNIFI_DATA_DIR}
[ -z "${UNIFI_LOG_DIR}" ] || LOGDIR=${UNIFI_LOG_DIR}
[ -z "${UNIFI_RUN_DIR}" ] || RUNDIR=${UNIFI_RUN_DIR}

systemd_helper=/usr/bin/deb-systemd-helper

systemd_remove() {
    [ -x ${systemd_helper} ] || return 0
    ${systemd_helper} mask ${NAME}.service > /dev/null
}

systemd_purge() {
    [ -x ${systemd_helper} ] || return 0
    ${systemd_helper} purge ${NAME}.service > /dev/null
    ${systemd_helper} unmask ${NAME}.service > /dev/null
}

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear)
        echo "$1: please reinstall previous version"
        echo ""
        echo "sudo apt-get install --reinstall unifi=$2"
        echo ""
        exit 2
    ;;

    remove|upgrade)
        systemd_remove
        update-rc.d -f unifi remove
    ;;

    purge)
        update-rc.d -f unifi remove
        systemd_purge
        [ ! -d ${DATADIR} ] || rm -rf ${DATADIR}
        [ ! -d ${LOGDIR} ] || rm -rf ${LOGDIR}
        [ ! -d ${RUNDIR} ] || rm -rf ${RUNDIR}

        . /usr/share/debconf/confmodule
        db_purge

        deluser ${UNIFI_USER:-unifi}
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0


