#!/bin/sh -e

. /usr/share/debconf/confmodule

if [ -f /var/lib/unifi/db/version ]; then
    echo "Previous setting (UniFi $(cat /var/lib/unifi/db/version)) is found."

    db_fset unifi/has_backup seen false
    db_input critical unifi/has_backup || true
    db_go

    db_get unifi/has_backup
    if [ "$RET" = "false" ]; then
        db_input critical unifi/err_no_backup || true
        db_go
        exit 2
    fi
fi
